### ISSUE TITLE
0.11B - many UPnP messages

### ISSUE THREAD

**Issue by ronohara** [bitcoinxt/bitcoinxt#72] opened 2015-09-14 10:51 UTC
At regular intervals the UPnP mapping seems to be done again. This is rather unexpected behaviour for me. I would have expected this at startup / shutdown, and perhaps if some network unreachable events occur.

However, this seems to happen at about 20 minute intervals.

2015-09-14 09:26:14 progress=0.999999  cache=51.7MiB(10478tx)
2015-09-14 09:34:46 Pre-allocating up to position 0xa00000 in rev00352.dat
2015-09-14 09:34:46 UpdateTip: new best=0000000000000000033ac13d7f4d3defee41e0ce2c34d1b190a88a582c595f91  height=374475  log2_work=83.34495  tx=83660397  date=2015-09-14 09:33:54 progress=0.999999  cache=64.7MiB(16762tx)
2015-09-14 09:38:53 UPnP Port Mapping successful.
2015-09-14 09:58:53 UPnP Port Mapping successful.
2015-09-14 10:09:07 UpdateTip: new best=000000000000000004260f338d0c65ff887d50320864e148e172201cdbc3866e  height=374476  log2_work=83.344979  tx=83662582  date=2015-09-14 10:12:50 progress=1.000003  cache=43.5MiB(10704tx)
2015-09-14 10:18:53 UPnP Port Mapping successful.
2015-09-14 10:25:20 UpdateTip: new best=000000000000000003783910316c65a836a613c62ed625dd639c7cc25c6d8c5e  height=374477  log2_work=83.345007  tx=83664123  date=2015-09-14 10:24:31 progress=0.999999  cache=59.4MiB(14948tx)
2015-09-14 10:26:52 UpdateTip: new best=00000000000000000ac9616939732fef37fcf40f25ab99fd35042973a5ea3255  height=374478  log2_work=83.345036  tx=83664292  date=2015-09-14 10:26:06 progress=0.999999  cache=7.4MiB(956tx)
2015-09-14 10:38:53 UPnP Port Mapping successful.

**Comment by zander** [comment] 2015-09-14 11:02
Unexpected is a bit of on reason to create a bugreport.

What actually is going wrong?  Is this behavior causing problems?

**Comment by ronohara** [comment] 2015-09-14 12:02
Any time I see what is essential log flooding, I start to question why.  Is this accidental behaviour, or deliberate. Either can indicate a problem.

The repeated programming of a flash based device (aka your router), depending on the design of that router, can cause lots of writes to flash - ultimately that will break the flash, and the router with it.

So - I ask, is this repeated UPnP update deliberate?  If so, what problem is this addressing, and is this the optimum way to solve the problem.

If it is an accidental action ... then it needs to be corrected.

Either way - there is nothing wrong raising this issue, and the only mechanism I have is the bug report.

**Comment by mikehearn** [comment] 2015-09-14 16:33
I agree it's odd. The code is clearly designed to do this but (surprise) there are no comments explaining why. Your guess is as good as ours here - you could try finding whoever wrote this code originally and asking them.

As there's no obvious problems being caused by this and nobody here knows the reason it works this way, I'm going to close this issue.

**Closed by mikehearn** 2015-09-14 16:33 UTC
